- name: Launch database container
  docker_container:
    name: database
    image: simonlucas/tp-devops-simple-api-database:latest
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: "{{ database_user }}"
      POSTGRES_PASSWORD: "{{ database_password }}"
      POSTGRES_DB: "{{ database_name }}"
    networks:
      - name: my-network
