- name: Launch simple-api container
  docker_container:
    name: simple-api
    image: simonlucas/tp-devops-simple-api-backend:latest
    state: started
    restart_policy: always
    published_ports:
      - "8080:8080"
    networks:
      - name: my-network
    env:
      DATABASE_HOST: "{{ database_host }}"
      DATABASE_PORT: "{{ database_port }}"
      DATABASE_NAME: "{{ database_name }}"
      DATABASE_USER: "{{ database_user }}"
      DATABASE_PASSWORD: "{{ database_password }}"
    